name: OldCMT
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26
  - pandas=1.5
  - geopandas
  - scipy
  - matplotlib
  - spyder
  - shapely
  - rasterio
  - gdal
  - pyshp
  - pip
  - openpyxl